import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import leaf from "../../Assets/Projects/leaf.png";
import emotion from "../../Assets/Projects/emotion.png";
import editor from "../../Assets/Projects/codeEditor.png";
import chatify from "../../Assets/Projects/chatify.png";
import local from "../../Assets/Projects/local.png";
import events from "../../Assets/Projects/events.png";
import music from "../../Assets/Projects/music.png";
import suicide from "../../Assets/Projects/suicide.png";
import bee from "../../Assets/Projects/bee.jpg";
import jeu2d from "../../Assets/Projects/jeu2d.jpg";
import bitsOfCode from "../../Assets/Projects/blog.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <p style={{ color: "white" }}>
          My two latest projects are not finished, but I am looking for a Team to help me bring these projects to life!
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={12} className="project-card">
            <ProjectCard
              imgPath={local}
              isBlog={false}
              title="FindLocalGuides"
              description="FindLocalGuides is an app that connects young travelers with local guides for unique, personalized experiences. Built using Next.js, TypeScript, and Prisma, the app lets users explore new destinations through the eyes of a local, whether it’s discovering hidden gems, diving into local culture, or enjoying vibrant nightlife. With features like seamless authentication and state management powered by NextAuth and Zustand, Pusher, Local Vibes offers an engaging platform for travelers. This project was coded while traveling through Thailand, in the hopes of creating a better future!"
              ghLink="https://github.com/soumyajit4419/Chatify"
              demoLink="https://findlocalguides.vercel.app/"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={events}
              isBlog={false}
              title="LocalEvents"
              description="LocalEvents is an app I created by myself while in school to help people find events and clubs in their area. It was built using React, Redux, and Firebase. The app allows users to search for events by location, date, and category, and to save events they’re interested in. Users can also create their own events and share them with others. I built this app to help people connect with their communities and have fun."
              ghLink="https://github.com/soumyajit4419/Bits-0f-C0de"
              demoLink="https://local-linky-ga9verjdn-timothes-projects-262d62a8.vercel.app/auth"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={music}
              isBlog={false}
              title="Soundwave"
              description="Soundwave is a Spotify clone I made as a school project as a Team of 4, I was the backend programmer. It was built using React and the spotify API, "
              ghLink="https://github.com/soumyajit4419/Editor.io"
              demoLink="https://sound-wave-liart.vercel.app/"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={bee}
              isBlog={false}
              title="Bees the game"
              description="3D videogame made with Unity. I was the programmer in this project and the land is being generated by prog to get a different level everytime. It had many difficult
               programming challenges and I am proud of the result."
              ghLink="https://github.com/soumyajit4419/Plant_AI"
              demoLink=""
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={jeu2d}
              isBlog={false}
              title="2D game"
              description="2D game made in Unity. It's a spelunky-like game that has levels generated by programmation. I did this game in my 4th class of video game programming."
              ghLink="https://github.com/timotheLeduc/Jeu4"
             demoLink="https://github.com/timotheLeduc/Jeu4" 
            />
          </Col>

        </Row>
      </Container>
    </Container>
  );
}

export default Projects;